"""Add cheese_type_id

Revision ID: 25e9ed130c58
Revises: ed860f0a283c
Create Date: 2025-05-13 14:34:15.002958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25e9ed130c58'
down_revision: Union[str, None] = 'ed860f0a283c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cheese', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'cheese_type', ['cheese_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cheese', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
