"""Initial migration

Revision ID: 4e8b3b878b94
Revises: d59c3e2a494b
Create Date: 2025-05-13 14:26:59.818404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e8b3b878b94'
down_revision: Union[str, None] = 'd59c3e2a494b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cheese', sa.Column('cheese_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cheese', 'cheese_type', ['cheese_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cheese', type_='foreignkey')
    op.drop_column('cheese', 'cheese_type_id')
    # ### end Alembic commands ###
