"""Initial migration

Revision ID: 742715346447
Revises: 326c7455b19f
Create Date: 2025-05-12 19:44:57.199123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '742715346447'
down_revision: Union[str, None] = '326c7455b19f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cheese',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('packaging_type', sa.Enum('BOX', 'BAG', 'WRAP', 'WEIGHT', 'OTHER', name='packagingtype'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_cheese_id'), 'cheese', ['id'], unique=False)
    op.create_table('cheese_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=511), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_cheese_type_id'), 'cheese_type', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cheese_type_id'), table_name='cheese_type')
    op.drop_table('cheese_type')
    op.drop_index(op.f('ix_cheese_id'), table_name='cheese')
    op.drop_table('cheese')
    # ### end Alembic commands ###
