"""Fix constraint names

Revision ID: ad24d6bc9e68
Revises: 25e9ed130c58
Create Date: 2025-05-13 14:36:05.261776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad24d6bc9e68'
down_revision: Union[str, None] = '25e9ed130c58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cheese', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_cheese_cheese_type_id', 'cheese_type', ['cheese_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cheese', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cheese_cheese_type_id', type_='foreignkey')

    # ### end Alembic commands ###
