"""Next migration

Revision ID: ed860f0a283c
Revises: 4e8b3b878b94
Create Date: 2025-05-13 14:31:07.688367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed860f0a283c'
down_revision: Union[str, None] = '4e8b3b878b94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cheese', 'cheese_type', ['cheese_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cheese', type_='foreignkey')
    # ### end Alembic commands ###
